### ISSUE TITLE
Add SFML libraries for Windows and MacOS

### ISSUE THREAD

**Issue by alesbe** [alesbe/sorting-visualizer#12]
## Describe you problem / suggestion:
CMake works as expected on Linux, but on Windows or macOS the project can't be build because the SFML libraries included with the project are only for Linux (GCC), so CMake can't be used on Windows or macOS.

## Steps to reproduce (optional):
- Clone the repository and try to build the project using CMake: `cmake -G "MinGW Makefiles" CMakeLists.txt` in Windows or macOS.

## Possible fix (optional):
Im not sure how to approach this issue, maybe adding libraries for Windows, Linux and macOS and detecting the OS in `CMakeLists.txt`, so the correct libraries can be included.

## OS
- [x] : Windows
- [x] : Mac OS
- [ ] : Linux

**Comment by alesbe** [comment]
We'll need to think about how to approach this, the total size of all the libraries is more than 20MB, is not *that* much but the visualizer itself is so much lightweight than all the libraries combined. If there was a library that worked cross-platform instead of different ones for each compiler would be the best solution.

Also, we could include pre-compiled binaries to the Release and download directly the visualizer compiled from there, but that would prevent anyone from contributing from any other plataform than Linux.

**Comment by alesbe** [comment]
We could compile SFML directly using CMake, that option seems the best and would be completely platform independent. https://www.sfml-dev.org/tutorials/2.5/compile-with-cmake.php

**Comment by alesbe** [comment]
I just saw that the SFML source code is also 20MB, in that case, the best approach would still be to include the libraries for each OS or think other alternatives

**Comment by bazuin-32** [comment]
I managed to get CMake to download and compile SFML itself through `FetchContent`, but it can take a while to download even with a shallow clone because of the size of SFML libraries. However, this only needs to happen once as long as you don't delete the build directory, and it removes the need for you to have SFML files in your own repo since CMake will get them for you.

I haven't tried this yet on windows/mac so I don't know for sure if it would work there but I would assume that it would since everything is being compiled through CMake.

What do you think? Is there a better solution? It also might be possible that the pre-compiled SFML binaries could be included as well, and people could choose which method to use.

**Comment by alesbe** [comment]
The thing about SFML is that the compiler version needs to match with the SFML version, for example, you can't use SFML for GCC and try to compile it with MinGW or Visual Studio 2019.

The visualizer itself is pretty lightweight, and I don't want to include SFML for each OS, so maybe `FetchContent` it's a good alternative. It would be great to download the SFML version according to the OS or compiler used detected by CMake or `install.sh`, but also downloading things would make the project less portable, maybe [compiling SFML with CMake](https://www.sfml-dev.org/tutorials/2.5/compile-with-cmake.php) instead of including the sfml lib for each OS? The sfml source code weights 20MB, and with CMake can be used to compile it for any OS or compiler.

What do you think? I don't know what is the best approach, I want to keep the visualizer lightweight but also like the idea of including the libraries with the project without downloading anything else.

**Comment by bazuin-32** [comment]
> It would be great to download the SFML version according to the OS or compiler used detected by CMake or install.sh, but also downloading things would make the project less portable

I'm assuming you mean downloading one of the `*.zip`/`*.tar.gz` from the [SFML releases](https://github.com/SFML/SFML/releases/tag/2.5.1) page, right? I agree that this would make the project less portable, and it feels like a bit of a workaround (if you know what I mean) because of how specific the versions are to the compiler. If there was only one version per OS, this would be a bit easier.

> maybe [compiling SFML with CMake](https://www.sfml-dev.org/tutorials/2.5/compile-with-cmake.php) instead of including the sfml lib for each OS

I'm thinking now that this is probably better, just because of its portability, it can be used by and OS/compiler that CMake works with, and the logic for adapting to the platform is already done for us. Maybe something like this would work?:
1. Call `find_package`, to see if SFML is already on the system, and if it is just use that. This would make it possible for people to install it any way they want beforehand, as long as CMake can find it.
2. If it's not there, then use `Fetch_Content` to download and compile it with CMake. This would only have to happen once, since the downloaded and compiled library is left in the build directory.

I'm still not 100% sure what to do though, both methods have their benefits and downsides.

**Comment by alesbe** [comment]
> I'm thinking now that this is probably better, just because of its portability, it can be used by and OS/compiler that CMake works with, and the logic for adapting to the platform is already done for us. Maybe something like this would work?:

Yeah, I think the same, the only downside is that the `./src` folder itself with the source code it's only 48KB, and the entire SFML library is more than 20MB, but seems like a better option rather than downloading sfml from external sources.

[Here](https://www.sfml-dev.org/tutorials/2.5/compile-with-cmake.php) is the documentation for building SFML using CMake, the visualizer itself only uses window, graphics and system from sfml, maybe including only the files related to those modules would reduce the size? For now we could build sfml and compile the project with that, I'm going to create a dev branch to push the changes until everything is done, just in case.

Do you want to solve this issue? Don't worry if it's too much, for now the visualizer it's working perfectly, this is just an implementation for Windows and macOS, up to you!

**Comment by bazuin-32** [comment]
> the ./src folder itself with the source code it's only 48KB, and the entire SFML library is more than 20MB

I'm not sure theres really anything we can do about this. After cloning the SFML git repo, I get this:
```bash
❯ du -sh * | sort -h
4.0K	CONTRIBUTING.md
4.0K	license.md
8.0K	readme.md
24K	CMakeLists.txt
28K	changelog.md
96K	cmake
152K	doc
164K	test
988K	tools
1.2M	include
1.3M	build
2.4M	src
3.3M	examples
56M	extlibs
```

Keep in mind these are the sizes for the uncompressed files, when downloading they would be compressed. Removing the `extlibs` folder prevents SFML from compiling. I suppose `examples`, `test`, etc. could be excluded, but they are a smaller percentage of the size, and I don't know how (if at all possible) to exclude these folders from `FetchContent`.

I'll be busy for most of today, but I can take a look at this tomorrow and see if I can get something working.

**Comment by alesbe** [comment]
I went to the [SFML downloads](https://www.sfml-dev.org/download/sfml/2.5.1/), and saw the source code at the bottom:
![source](https://i.imgur.com/T8mCuxr.png)

I don't know if that is what is supposed to be built with CMake, that's why I was concerned about the 20MB. I'll look into it.

> I'll be busy for most of today, but I can take a look at this tomorrow and see if I can get something working.

Sure, don't worry!

**Comment by alesbe** [comment]
After considering the different approaches for this issue, I prefer to include only the gcc libraries for now. Maybe I'll include a pre-compiled version for Windows on Releases.
