### ISSUE TITLE
Clean CMake files after building

### ISSUE THREAD

**Issue by alesbe** [alesbe/sorting-visualizer#13]
## Describe you problem / suggestion:
CMake generates a lot of files while building, it would be nice to generate those files in a temporary folder and then remove it using `install.sh` when the build is completed.

## Steps to reproduce (optional):
*None*

## Possible fix (optional):
Edit `install.sh` and/or `CMakeLists.txt` to not generate all the files in the root directory.

## OS
- [ ] : Windows
- [ ] : Mac OS
- [x] : Linux

**Comment by bazuin-32** [comment]
I implemented this, but didn't remove the subdirectory since leaving it there allows CMake to do 'incremental' builds, when you change a file and rebuild then it only needs to recompile that file, and can reuse the compiled `*.o`s for the rest of the code. Removing the build directory deletes these object files, so this ability is lost.

Let me know if this works for you or if I should make the script remove the build directory and then I'll submit the PR.

**Comment by alesbe** [comment]
Sure, I didn't think about that, keeping the folder seems like a better idea, do the PR if you want :)
