### ISSUE TITLE
Possible data race

### ISSUE THREAD

**Issue by ghost** [alesbe/sorting-visualizer#6]
There appears to be a shared resource between threads without any kind of locking/access control. I fear this may lead to data races. (Mind my relative inexperience with parallel programming.)

[edit: the correct term is "race condition"]

On main:
https://github.com/alesbe/sorting-visualizer/blob/72efc534540def28b525f6722e1d3a15f5e060e7/main.cpp#L135

Also here among other points of access:
https://github.com/alesbe/sorting-visualizer/blob/72efc534540def28b525f6722e1d3a15f5e060e7/main.cpp#L108

On sorting worker:
https://github.com/alesbe/sorting-visualizer/blob/72efc534540def28b525f6722e1d3a15f5e060e7/SortController.cpp#L72

The worker thread could still be writing the elements in the sort container while main is reading it. Main could then end up with an invalid object/data.

A simple way to reproduce this is to hit F1 immediately after beginning a sort (bubble in my case). Where the worker will then try to access elements that are no longer there. I worry that danger maybe present in line 135 on main, even if it's unlikely.

(Anyhow hope this issue is helpful/useful.)

**Comment by alesbe** [comment]
I also don't have too much experience in parallel programming, this is where the thread is created:
https://github.com/alesbe/sorting-visualizer/blob/e8569dff76cdbf1345fc946f8148071bc4ba1183/main.cpp#L57-L59

Maybe the fact that the sorting process is running in a detached thread is causing similar issues, I think that the ideal solution is to run the thread without being detached and do `sortingThread.join()` when the sorting process finish, stop or changed any configuration, the disadvantage of running the thread detached is that you don't have any way to manually stop the thread until it finishes.

**Comment by alesbe** [comment]
Commit https://github.com/alesbe/sorting-visualizer/commit/82613faa8142cb732c72c15a59f626777a9fb094 now prevents the user from changing the settings while the algorithm is running, that should fix the bug when trying to change something immediately after the algorithms starts, now to change settings you need to stop the current algorithm before anything else.

`SortController` is being shared between the threads because the main one needs to draw the elements while the other performs the algorithm. Maybe there is a proper way to do that, like joining the thread when the algorithm finishes or is manually stopped instead of detaching the thread.

I'm closing this for now because the bug is not happening anymore, but I'll look into it if there are any more issues.

Thanks! 🙌
